Feature/calendar updating
Scouting-Lommel/sl-website-fe pull request #32
Opened 2023-08-16 09:01 UTC by VincentWijshoff

- When navigating to the path /verhuur/settings/revalidate the bookings get revalidated from the google calendar
- A bit of UI is created to make it easyer to see the status of the revalidator
- Under no circomstances should any link be created to this ath, it is a more intensive opperation on the backend and must thus only be called when neccesary, only the needed people must know about this path and functionality
- When this gets approved, the calendar repo can be removed as all funcitonality from that repo will be integrated in the site

2023-09-19 19:37 UTC, seppealaerts requested changes
## Code review
- Let op filename conventions
- Ook bij de branch name zelf: geen underscore, gebruik dashes
- Gebruik meaningful variables

## Visual review
- Geen POC gevonden

2023-09-19 19:37 UTC, seppealaerts commented on src/components/atoms/Loader/loader.pcss
> +  border-top: 16px solid var(--color-theme-secondary);
`1rem`

2023-09-19 19:37 UTC, seppealaerts commented on src/components/atoms/Loader/loader.pcss
> +  width: 120px;
`7.5rem`

2023-09-19 19:37 UTC, seppealaerts commented on src/pages/api/revalidate_calendar/strapiCalendar.tsx
Geen camelCase in urls/paths, gebruik dashes `strapi-calendar.tsx`

2023-09-19 19:37 UTC, seppealaerts commented on src/pages/api/revalidate_calendar/getBookings.gql
> +  bookings(pagination: { start: 0, limit: 10000 }) {
Waarom pagination als je het limiet zo hoog zet?

2023-09-19 19:37 UTC, seppealaerts commented on src/components/molecules/CalendarRevalidator/index.tsx
> +  const [currState, setState] = useState(<Loader />);
`[currState, setCurrState]`

2023-09-19 19:37 UTC, seppealaerts commented on src/components/molecules/CalendarRevalidator/index.tsx
> +  const [isHandling, setHandling] = useState(false);
`[isHandling, setIsHandling]`

2023-09-19 19:37 UTC, seppealaerts commented on src/components/molecules/CalendarRevalidator/index.tsx
> +      <BlockContainer variant="dark" orientation="default" slug="calendarRevalidator">
Geen camelCase in slugs, gebruik dashes `calendar-revalidator`

2023-09-19 19:37 UTC, seppealaerts commented on src/components/molecules/CalendarRevalidator/index.tsx
> +        <h2 className="revalidator">{currState}</h2>
Geen child component(`<Loader />`) zonder copy in een `<h2 />`

2023-09-19 19:37 UTC, seppealaerts commented on src/pages/api/revalidate_calendar/googleCalendar.tsx
> +      const syear = start.getFullYear();
Gebruik meaningful variables. `startYear`, `startDay`, `endYear`, ...

2023-09-19 19:37 UTC, seppealaerts commented on src/pages/api/revalidate_calendar/googleCalendar.tsx
> +        StartDate: sdateString,
Is er een reden waarom deze keys een hoofdletter hebben? Indien niet -> camelCase

2023-09-19 19:37 UTC, seppealaerts commented on src/pages/api/revalidate_calendar/index.tsx
> +        StartDate: dbDate.attributes.start,
Hier lijkt me PascalCase ook niet nodig te zijn, mag gewoon camelCase

2023-09-19 19:37 UTC, seppealaerts commented on src/pages/api/revalidate_calendar/index.tsx
> +  } catch (e) {
Meaningful variables: `error`

2023-09-20 09:43 UTC, VincentWijshoff commented on src/pages/api/revalidate_calendar/getBookings.gql
> +  bookings(pagination: { start: 0, limit: 10000 }) {
Omdat er automatisch pagination gedaan wordt met een limiet van 10, dus zonder krijg ik maar 10 results.

2023-09-20 10:08 UTC, merged