feature/filesAndLinks
Scouting-Lommel/sl-website-fe pull request #36
Opened 2023-08-24 12:20 UTC by VincentWijshoff

2023-09-28 20:40 UTC, seppealaerts requested changes
## General remarks
Probeer git op een correcte, overzichtelijkere manier te gebruiken:
- Schrijf atomic commits: bij elke (sub)mijlpaal committen. Bijvoorbeeld na het schrijven van een query, het neerleggen van de basic HTML structuur van een component, de styling van een component, het schrijven van een (sub)feature...
- Een commit begint met een hoofdletter, is geschreven in het engels en bevat geen spelfouten
- Een commit vormt een volzin als men er de woorden "This commit will" voorzet. Bijvoorbeeld: "This commit will `Add basic HTML outline for File component` / `Remove unused imports` / `Optimize async load times`"

## Code review
- We moeten nog een uniformiteit vinden in de icons. We gebruiken locale icons en FontAwesome door elkaar, en de locale hebben geen eenzijdige stijl.
- The usual suspects: filenames, BEM, variables, etc.

## Visual review
- Ziet er prima uit, kan ook nog wel wat meer richting het figma design
- Er is nog wat extra margin nodig tussen de titel en de files
- De files best in een nieuw tab openen. Zet een 'open in nieuw tabblad' achter de filename

2023-09-28 20:40 UTC, seppealaerts commented on src/app/takken/[slug]/page.tsx
> +  for (let i = 0; i < group.attributes.blocks.length; i++) {
Dit kan ook prima met `group.attributes.blocks.forEach((block) => { // ... })`

2023-09-28 20:40 UTC, seppealaerts commented on src/components/atoms/Icon/Icon.pcss
> +  &--custom {
Custom? Maak hier dan de `xl` van, en rename de `xl` naar `xxl`

2023-09-28 20:40 UTC, seppealaerts commented on src/components/molecules/File/File.pcss
> +
Lege lijn verwijderen

2023-09-28 20:40 UTC, seppealaerts commented on src/components/molecules/File/File.pcss
- Gebruik BEM
- Gebruik snake-case
- Gebruik variables
- Gebruik rem

2023-09-28 20:40 UTC, seppealaerts commented on src/components/molecules/File/index.tsx
> +'use client';
Deze kan prima op de server gerenderd worden lijkt me?

2023-09-28 20:40 UTC, seppealaerts commented on src/assets/icons/unknown_file.svg
Rename de filename naar `UnknownFile.svg`

2023-09-28 20:40 UTC, seppealaerts commented on src/assets/icons/jpg.svg
Icon filenames beginnen met een hoofdletter, misschien hier dan best `JPG.svg` van maken.

2023-09-28 20:40 UTC, seppealaerts commented on src/components/molecules/File/index.tsx
> +      className={classNames('fileContainer', final && 'fileContainer__final')}
Die `final` kan je vrij proper oplossen met een css `:last-child` selector

2023-09-28 20:40 UTC, seppealaerts commented on src/components/molecules/File/types.ts
> +  final?: boolean;
Deze is niet meer nodig

2023-09-28 20:40 UTC, seppealaerts commented on src/components/organisms/FileSection/FileSection.pcss
- Herbekijk de classnames nog eens
- Gebruik variables, rem

2023-10-04 16:41 UTC, VincentWijshoff commented on src/components/molecules/File/index.tsx
> +'use client';
Custom onclick events moeten ook client side

2023-10-04 17:05 UTC, merged